### ISSUE TITLE
Login > Cadastre-se > Alterar "nome de usuário" para "nome da ONG".

### ISSUE THREAD

**Issue by isaacsamuel002** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-doeaqui#54]

**Comment by Zattrus** [comment]
![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-doeaqui/assets/62392872/6045509d-a30b-4e28-aaae-79d82f4786a4)


Remover "razão social" e substituir para "nome da ONG"
